
const constant = {

    SET_CUSTOMERS: 'SET_CUSTOMERS',
    SET_SELECTED_CUSTOMER: 'SET_SELECTED_CUSTOMER',
    SET_REBATE_RULE: 'SET_REBATE_RULE',
    SET_CUSTOMER_RULE: 'SET_CUSTOMER_RULE',
    SET_ORDERS: 'SET_ORDERS',
    SET_TOTAL: 'SET_TOTAL'
}

export default constant
